# Install pre-commit hooks via
# pre-commit install

repos:

  # - repo: git://github.com/pre-commit/pre-commit-hooks
  #   rev: v2.2.3
  #   hooks:
  #   - id: check-json
  #   - id: check-yaml
  #   - id: end-of-file-fixer
  #   - id: trailing-whitespace

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.7.9
  #   hooks:
  #   - id: flake8

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
